---
  - name: Template cloud-config for boxrole
    template: "src=cloud-config.j2 dest=/home/core/cloud-config.yaml"

  - name: Template clean for boxrole
    template: "src=clean.sh.j2 dest=/home/core/clean.sh mode=0770"

  - name: Ensure /var/lib/coreos-install exists
    file: path=/var/lib/coreos-install state=directory

  - name: Template cloud-config to permanent user_data
    template: "src=cloud-config.j2 dest=/var/lib/coreos-install/user_data"

  - name: Initialize coreos with cloud config
    shell: coreos-cloudinit --from-file=/home/core/cloud-config.yaml
